<?php
/**
 * @author Karol Kowalewski <sensejszyn@gmail.com>
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<span data-action="toggle-nav" class="action nav-toggle">
    <span><?= $block->escapeHtml(__('Toggle Nav')) ?></span>

    <svg width="24px" height="24px" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g>
            <rect fill="#FFFFFF" height="0.75" width="11" x="0.5" y="5.5"/>
            <rect fill="#FFFFFF" height="0.75" width="11" x="0.5" y="2.5"/>
            <rect fill="#FFFFFF" height="0.75" width="11" x="0.5" y="8.5"/>
        </g>
    </svg>
</span>
